POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "testUser",
  "email": "testUser@test2.com",
  "password": "Password123_"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "testUser@test2.com",
  "password": "Password123_"
}

###

POST http://localhost:3000/api/cart/add/3/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RVc2VyQHRlc3QyLmNvbSIsInN1YiI6eyJpZCI6MywibmFtZSI6InRlc3RVc2VyIn0sImlhdCI6MTcwODk1MTY3OCwiZXhwIjoxNzA5NTU2NDc4fQ.96Ui-5D58IulsTS_T8-f0fqCUWqdLcrAMjhAOfcFkkE

{
  "quantity": 1
  }

###

GET http://localhost:3000/api/cart/items/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RVc2VyQHRlc3QyLmNvbSIsInN1YiI6eyJpZCI6MywibmFtZSI6InRlc3RVc2VyIn0sImlhdCI6MTcwODk1MTY3OCwiZXhwIjoxNzA5NTU2NDc4fQ.96Ui-5D58IulsTS_T8-f0fqCUWqdLcrAMjhAOfcFkkE

###

GET http://localhost:3000/api/cart/total/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RVc2VyQHRlc3QyLmNvbSIsInN1YiI6eyJpZCI6MywibmFtZSI6InRlc3RVc2VyIn0sImlhdCI6MTcwODk1MTY3OCwiZXhwIjoxNzA5NTU2NDc4fQ.96Ui-5D58IulsTS_T8-f0fqCUWqdLcrAMjhAOfcFkkE

