POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "testUser",
  "email": "testUser@test.com",
  "password": "Password123_"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "testUser@test.com",
  "password": "Password123_"
}